# Generated by Django 4.1.5 on 2023-06-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joint_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastener',
            name='E',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fastener',
            name='dia',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='E',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
